CLIBS=./lib/
_SRC=./src/
ODIR=./obj/
INC=-I$(CLIBS)
SRC=test.c

CC=cl
# Debug flags: /Zi /MT /EHsc /Oy- /Ob0
# Normal compile flags: -W2 -O1
CFLAGS=/Zi /MT /EHsc /Oy- /Ob0 /analyze

_DEPS=$(_SRC)$(SRC) $(CLIBS)utils.c $(CLIBS)sha3.c

_OBJ=$(ODIR)$(SRC) $(ODIR)utils.c $(ODIR)sha3.c
OBJ=$(_OBJ:.c=.obj)

sha3_tests.exe: $(OBJ)
	$(CC) $** $(CFLAGS)

$(OBJ)%.obj: $(_DEPS) 
	$(CC) -c /Fo$(ODIR) $** $(CFLAGS) $(INC)

